module.exports = [
  {
    userId: 1,
    id: 1,
    title: "How to kill a Vampire",
    body: `Vampires are creatures with a long and complex mythology. There are, however, a few basic rules that never change. It's part of what makes them vampires. If you intend to include vampires as part of a novel, or as part of cosplay or role-playing, you should know the basic rules for killing them off. Even though there can be quite a lot of variation, there are some basic rules you should follow for killing vampires. You can even adjust some of these tactics using clever wordplay or modern technology to widen the possibilities of your vampire story.`,
    image: "post-1.jpeg",
    likes: 4,
    views: 20,
    date: new Date(),
  },
  {
    userId: 2,
    id: 2,
    title: "Demons spell",
    body: `Exorcizamus te, omnis immundus spiritus, omnis satanica potestas, omnis incursio infernalis adversarii, omnis legio, omnis congregatio et secta diabolica. Ergo, omnis legio diabolica, adiuramus te... cessa decipere humanas creaturas, eisque æternæ perditionìs venenum propinare... Vade, satana, inventor et magister omnis fallaciæ, hostis humanæ salutis... Humiliare sub potenti manu Dei; contremisce et effuge, invocato a nobis sancto et terribili nomine... quem inferi tremunt... Ab insidiis diaboli, libera nos, Domine. Ut Ecclesiam tuam secura tibi facias libertate servire, te rogamus, audi nos`,
    image: "post-2.jpeg",
    likes: 2,
    views: 15,
    date: new Date(),
  },
  {
    userId: 3,
    id: 3,
    title: "Crossroad Demon",
    body: `Crossroad Demons are demons tasked with "buying" souls for Hell through deals with humans. These deals consist of the demon granting the human's wish in exchange for ownership over that person's soul, resulting in the person dying and going to Hell to be transformed into a demon upon death. Crossroad demons are named as such because they, in particular, can be summoned at crossroads by humans seeking to make deals.`,
    image: "post-3.jpeg",
    likes: 24,
    views: 61,
    date: new Date(),
  },
  {
    userId: 4,
    id: 4,
    title: "Angel Tablet",
    body: `The Angel Tablet is one of three known Words of God. It pertains the nature of Angels as well as granting unimaginable power to Angels who have a connection with it.`,
    image: "post-4.jpeg",
    likes: 11,
    views: 20,
    date: new Date(),
  },
];
